import random

CHEERS = [
    ('Afrikaans', 'Gesondheid'),
    ('Albanian', 'Gëzuar'),
    ('Armenian (Western)', 'Կէնաձդ'),
    ('Azerbaijani', 'Nuş olsun'),
    ('Bosnian', 'Živjeli'),
    ('Bulgarian', 'Наздраве'),
    ('Burmese', 'Aung myin par say'),
    ('Catalan', 'Salut'),
    ('Chamorro (Guam)', 'Biba'),
    ('Chinese (Mandarin)', '干杯 (gān bēi)'),
    ('Croatian', 'Živjeli'),
    ('Czech', 'Na zdravi'),
    ('Danish', 'Skål'),
    ('Dutch', 'Proost'),
    ('English', 'Cheers'),
    ('Estonian', 'Terviseks'),
    ('Filipino/Tagalog', 'Mabuhay'),
    ('Finnish', 'Kippis'),
    ('French', 'Santé'),
    ('Galician', 'Salud'),
    ('German', 'Prost'),
    ('Greek', 'ΥΓΕΙΑ'),
    ('Hawaiian', 'Å’kålè ma’luna'),
    ('Hungarian', 'Egészségedre'),
    ('Icelandic', 'Skál'),
    ('Irish Gaelic', 'Sláinte'),
    ('Italian', 'Salute'),
    ('Italian', 'Cin cin'),
    ('Japanese', '乾杯 (Kanpai)'),
    ('Korean', '건배'),
    ('Latvian', 'Priekā'),
    ('Lithuanian', 'į sveikatą'),
    ('Macedonian', 'На здравје'),
    ('Mongolian', 'Эрүүл мэндийн төлөө (Tulgatsgaaya)'),
    ('Norwegian', 'Skål'),
    ('Polish', 'Na zdrowie'),
    ('Portuguese', 'Saúde'),
    ('Romanian', 'Noroc'),
    ('Russian', 'Будем здоровы'),
    ('Serbian', 'živeli'),
    ('Slovak', 'Na zdravie'),
    ('Slovenian', 'Na zdravje'),
    ('Spanish', 'Salud'),
    ('Swedish', 'Skål'),
    ('Thai', 'Chok dee'),
    ('Turkish', 'Şerefe'),
    ('Ukranian', 'будьмо'),
    ('Vietnamese', 'Dô'),
    ('Vietnamese', 'Vô'),
    ('Vietnamese', 'Một hai ba, yo (one, two, three, yo)'),
    ('Welsh', 'Iechyd da'),
    ('Yiddish', 'Sei gesund'),
]


def cheers():
    language, cheer = random.choice(CHEERS)
    return '%s! (Now you know how to say cheers in %s!)' % (cheer, language)
